"""Loader for 3D Helmholtz single/double-layer matrices generated by gen_SD_3D.py.

The 3D analog of ``wave_scattering_utils.load_SD_matrices`` for 2D.  The 2D
matrices come from a MATLAB chunkIE driver and are shipped as ``.mat`` files;
the 3D matrices come from ``examples/gen_SD_3D.py`` (which uses fmm3dbie under
the hood) and are shipped as ``.npz``.

The matrices are stored in fmm3dbie's natural node ordering (faces in order
xmin, xmax, ymin, ymax, zmin, zmax, each face flattened with row-major
``indexing="xy"`` over tensor-product GL nodes).  This generally does NOT
match the order produced by ``Domain.boundary_points``, which uses
``indexing="ij"`` and has a different per-face axis convention forced by the
outward-normal requirement of fmm3dbie's quad patches.  The
``permute_to_domain`` helper computes the permutation between the two by
matching 3D positions, so callers can work entirely in the domain's ordering.
"""

import numpy as np
import jax.numpy as jnp
from typing import Tuple


def load_SD_matrices_3D(
    fp: str,
) -> dict:
    """Read the .npz produced by ``gen_SD_3D.py``.

    Returns a dict with the matrices and metadata; nothing is converted to JAX
    here because callers may want to permute before pushing to device.
    """
    d = np.load(fp, allow_pickle=False)
    out = dict(
        S=d["S"],
        D=d["D"],
        wts=d["wts"],
        boundary_points=d["boundary_points"],
        normals=d["normals"],
        face_idx=d["face_idx"],
        a=float(d["a"]),
        q=int(d["q"]),
        L=int(d["L"]),
        kappa=float(d["kappa"]),
        eps=float(d["eps"]),
    )
    return out


def permute_to_domain(
    sd_data: dict,
    domain_boundary_points: np.ndarray,
    atol: float = 1e-10,
) -> Tuple[np.ndarray, dict]:
    """Find the permutation ``P`` such that ``boundary_points[P] == domain_boundary_points``.

    Both node sets must be the same set of points; only the ordering differs.
    Internally uses an O(N log N) k-d tree lookup; raises if the nearest match
    for any domain point exceeds ``atol`` or if the resulting map is not a
    bijection (which would indicate an actual mismatch, not just a reordering).

    Returns ``(P, permuted)`` where ``permuted`` is a fresh dict mirroring
    ``sd_data`` with ``S, D, wts, boundary_points, normals, face_idx`` all
    reordered so row/column ``i`` corresponds to ``domain_boundary_points[i]``.
    """
    from scipy.spatial import cKDTree

    bp_src = np.asarray(sd_data["boundary_points"])
    bp_dst = np.asarray(domain_boundary_points)
    if bp_src.shape != bp_dst.shape:
        raise ValueError(
            f"boundary point set sizes differ: "
            f"npz has {bp_src.shape}, domain has {bp_dst.shape}.  "
            f"Did you generate the matrices for the matching (q, L, a)?"
        )

    tree = cKDTree(bp_src)
    dists, P = tree.query(bp_dst, k=1)
    max_d = float(np.max(dists))
    if max_d > atol:
        raise ValueError(
            f"could not match domain boundary points to the npz set: "
            f"max nearest-neighbor distance {max_d:.3e} > atol={atol:.1e}.  "
            f"Likely cause: (a, q, L) mismatch between generation and Domain."
        )
    if len(set(P.tolist())) != len(P):
        raise ValueError(
            "node match was not a bijection -- duplicate sources mapped to "
            "the same domain target.  This should be impossible if the two "
            "point sets agree set-wise."
        )

    permuted = dict(sd_data)
    permuted["boundary_points"] = bp_src[P]
    permuted["normals"] = np.asarray(sd_data["normals"])[P]
    permuted["face_idx"] = np.asarray(sd_data["face_idx"])[P]
    permuted["wts"] = np.asarray(sd_data["wts"])[P]
    permuted["S"] = np.asarray(sd_data["S"])[np.ix_(P, P)]
    permuted["D"] = np.asarray(sd_data["D"])[np.ix_(P, P)]
    return P, permuted


def as_jax(sd_data: dict) -> dict:
    """Convert numerical arrays in the dict to ``jax.numpy`` arrays in place-of-copy."""
    out = dict(sd_data)
    for k in ("S", "D", "wts", "boundary_points", "normals", "face_idx"):
        out[k] = jnp.asarray(sd_data[k])
    return out
