"""Loader for 3D Helmholtz single/double-layer matrices generated by gen_SD_3D.py.

The 3D analog of ``wave_scattering_utils.load_SD_matrices`` for 2D.  The 2D
matrices come from a MATLAB chunkIE driver and are shipped as ``.mat`` files;
the 3D matrices come from ``examples/gen_SD_3D.py`` (which uses fmm3dbie under
the hood) and are shipped as ``.npz``.

The matrices are stored in fmm3dbie's natural node ordering (faces in order
xmin, xmax, ymin, ymax, zmin, zmax, each face flattened with row-major
``indexing="xy"`` over tensor-product GL nodes).  This generally does NOT
match the order produced by ``Domain.boundary_points``, which uses
``indexing="ij"`` and has a different per-face axis convention forced by the
outward-normal requirement of fmm3dbie's quad patches.  The
``permute_to_domain`` helper computes the permutation between the two by
matching 3D positions, so callers can work entirely in the domain's ordering.
"""

import os
import time

import numpy as np
import jax
import jax.numpy as jnp
from typing import Callable, Tuple

from jaxhps import (
    DiscretizationNode3D,
    Domain,
    PDEProblem,
    build_solver,
)

_TIMING = bool(os.environ.get("JAXHPS_TIMING"))


def _tic():
    return time.perf_counter()


def _toc(label, t0):
    if _TIMING:
        print(
            f"  [timing] {label}: {time.perf_counter() - t0:.2f}s", flush=True
        )
    return time.perf_counter()


def load_SD_matrices_3D(
    fp: str,
) -> dict:
    """Read the .npz produced by ``gen_SD_3D.py``.

    Returns a dict with the matrices and metadata; nothing is converted to JAX
    here because callers may want to permute before pushing to device.
    """
    d = np.load(fp, allow_pickle=False)
    out = dict(
        S=d["S"],
        D=d["D"],
        wts=d["wts"],
        boundary_points=d["boundary_points"],
        normals=d["normals"],
        face_idx=d["face_idx"],
        a=float(d["a"]),
        q=int(d["q"]),
        L=int(d["L"]),
        kappa=float(d["kappa"]),
        eps=float(d["eps"]),
    )
    return out


def permute_to_domain(
    sd_data: dict,
    domain_boundary_points: np.ndarray,
    atol: float = 1e-10,
) -> Tuple[np.ndarray, dict]:
    """Find the permutation ``P`` such that ``boundary_points[P] == domain_boundary_points``.

    Both node sets must be the same set of points; only the ordering differs.
    Internally uses an O(N log N) k-d tree lookup; raises if the nearest match
    for any domain point exceeds ``atol`` or if the resulting map is not a
    bijection (which would indicate an actual mismatch, not just a reordering).

    Returns ``(P, permuted)`` where ``permuted`` is a fresh dict mirroring
    ``sd_data`` with ``S, D, wts, boundary_points, normals, face_idx`` all
    reordered so row/column ``i`` corresponds to ``domain_boundary_points[i]``.
    """
    from scipy.spatial import cKDTree

    bp_src = np.asarray(sd_data["boundary_points"])
    bp_dst = np.asarray(domain_boundary_points)
    if bp_src.shape != bp_dst.shape:
        raise ValueError(
            f"boundary point set sizes differ: "
            f"npz has {bp_src.shape}, domain has {bp_dst.shape}.  "
            f"Did you generate the matrices for the matching (q, L, a)?"
        )

    tree = cKDTree(bp_src)
    dists, P = tree.query(bp_dst, k=1)
    max_d = float(np.max(dists))
    if max_d > atol:
        raise ValueError(
            f"could not match domain boundary points to the npz set: "
            f"max nearest-neighbor distance {max_d:.3e} > atol={atol:.1e}.  "
            f"Likely cause: (a, q, L) mismatch between generation and Domain."
        )
    if len(set(P.tolist())) != len(P):
        raise ValueError(
            "node match was not a bijection -- duplicate sources mapped to "
            "the same domain target.  This should be impossible if the two "
            "point sets agree set-wise."
        )

    permuted = dict(sd_data)
    permuted["boundary_points"] = bp_src[P]
    permuted["normals"] = np.asarray(sd_data["normals"])[P]
    permuted["face_idx"] = np.asarray(sd_data["face_idx"])[P]
    permuted["wts"] = np.asarray(sd_data["wts"])[P]
    permuted["S"] = np.asarray(sd_data["S"])[np.ix_(P, P)]
    permuted["D"] = np.asarray(sd_data["D"])[np.ix_(P, P)]
    return P, permuted


def outward_normals_for_cube_boundary(
    boundary_points: np.ndarray, root
) -> np.ndarray:
    """Outward unit normals at the cube's boundary nodes, identified by face.

    ``root`` is any object with ``xmin .. zmax`` attributes (e.g. a
    ``DiscretizationNode3D``).
    """
    n = np.zeros_like(boundary_points)
    eps = 1e-9
    n[np.abs(boundary_points[:, 0] - root.xmin) < eps] = [-1, 0, 0]
    n[np.abs(boundary_points[:, 0] - root.xmax) < eps] = [1, 0, 0]
    n[np.abs(boundary_points[:, 1] - root.ymin) < eps] = [0, -1, 0]
    n[np.abs(boundary_points[:, 1] - root.ymax) < eps] = [0, 1, 0]
    n[np.abs(boundary_points[:, 2] - root.zmin) < eps] = [0, 0, -1]
    n[np.abs(boundary_points[:, 2] - root.zmax) < eps] = [0, 0, 1]
    return n


# ---------------------------------------------------------------------------
# FMM-accelerated BIE -- replaces dense S, D with FMM + near-field correction
# ---------------------------------------------------------------------------


def _patch_indices(n_bdry: int, q: int, L: int) -> np.ndarray:
    """Return (n_patches, q^2) array of node indices grouped by patch."""
    q2 = q * q
    n_patches = n_bdry // q2
    return np.arange(n_bdry).reshape(n_patches, q2)


def build_nearfield_correction(
    sd: dict,
    bdry_pts: np.ndarray,
    normals: np.ndarray,
    wts: np.ndarray,
    q: int,
    L: int,
    kappa: float,
    fmm_eps: float = 1e-7,
    near_ratio: float = 4.0,
) -> dict:
    """Precompute additive near-field correction for FMM layer potentials.

    The dense matrices S, D from ``sd`` include accurate singular quadrature.
    The FMM evaluates the smooth kernel everywhere (excluding self) but is
    inaccurate for near interactions and misses the self-interaction entirely.

    The correction matrix C satisfies  S @ v = FMM_S(v) + C_S @ v  for each
    layer, where the correction is nonzero only in near-field blocks.

    Parameters
    ----------
    sd : dict from ``load_SD_matrices_3D`` (permuted to domain order).
    bdry_pts, normals, wts : (n_bdry, 3), (n_bdry, 3), (n_bdry,).
    q, L : boundary quadrature order and octree levels.
    kappa : wavenumber.
    fmm_eps : FMM tolerance (must match what will be used at solve time).
    near_ratio : patch pairs within ``near_ratio * patch_width`` are "near".

    Returns a dict with sparse CSR correction matrices and metadata.
    """
    from scipy.sparse import csr_matrix

    n_bdry = bdry_pts.shape[0]
    q2 = q * q
    patches = _patch_indices(n_bdry, q, L)
    n_patches = patches.shape[0]

    # Patch centers and widths for near-field detection
    patch_centers = np.array(
        [bdry_pts[patches[ip]].mean(axis=0) for ip in range(n_patches)]
    )
    patch_widths = np.array(
        [
            np.max(np.ptp(bdry_pts[patches[ip]], axis=0))
            for ip in range(n_patches)
        ]
    )
    max_pw = patch_widths.max()
    threshold = near_ratio * max_pw

    # Identify near patch pairs
    from scipy.spatial import cKDTree

    tree = cKDTree(patch_centers)
    near_pairs = []  # (i, j) patch-level
    for ip in range(n_patches):
        neighbors = tree.query_ball_point(patch_centers[ip], threshold)
        for jp in neighbors:
            near_pairs.append((ip, jp))

    S_dense = np.asarray(sd["S"])
    D_dense = np.asarray(sd["D"])

    # Smooth kernel blocks (what FMM would give for these pairs)
    def _smooth_kernel_block(row_idx, col_idx):
        """G(x_i, y_j) * w_j for the single layer; dG/dn_y * w_j for double."""
        xi = bdry_pts[row_idx][:, None, :]  # (ni, 1, 3)
        yj = bdry_pts[col_idx][None, :, :]  # (1, nj, 3)
        diff = xi - yj  # (ni, nj, 3)
        r = np.linalg.norm(diff, axis=-1)  # (ni, nj)
        wj = wts[col_idx]

        # Single layer: G * w_j
        with np.errstate(divide="ignore", invalid="ignore"):
            G = np.exp(1j * kappa * r) / (4.0 * np.pi * r)
        S_smooth = G * wj[None, :]
        # Self-interaction (r=0): FMM skips these, so smooth contribution = 0
        S_smooth[r == 0] = 0.0

        # Double layer: dG/dn_y * w_j
        # diff = x_i - y_j; dG/dn_y = (1/r - ik)(n_y . diff)/r * G
        nj = normals[col_idx]  # (nj, 3)
        n_dot_diff = np.einsum("ijk,jk->ij", diff, nj)  # (ni, nj)
        with np.errstate(divide="ignore", invalid="ignore"):
            dGdny = (1.0 / r - 1j * kappa) / r * G * n_dot_diff
        D_smooth = dGdny * wj[None, :]
        D_smooth[r == 0] = 0.0

        return S_smooth, D_smooth

    # Build sparse correction: C = exact_near - smooth_near (block-wise)
    n_pairs = len(near_pairs)
    rows_arr = np.empty(n_pairs * q2 * q2, dtype=np.int64)
    cols_arr = np.empty(n_pairs * q2 * q2, dtype=np.int64)
    S_vals = np.empty(n_pairs * q2 * q2, dtype=np.complex128)
    D_vals = np.empty(n_pairs * q2 * q2, dtype=np.complex128)

    idx = 0
    for ip, jp in near_pairs:
        ri = patches[ip]
        ci = patches[jp]
        S_exact = S_dense[np.ix_(ri, ci)]
        D_exact = D_dense[np.ix_(ri, ci)]
        S_smooth, D_smooth = _smooth_kernel_block(ri, ci)

        block_size = q2 * q2
        rr, cc = np.meshgrid(ri, ci, indexing="ij")
        rows_arr[idx : idx + block_size] = rr.ravel()
        cols_arr[idx : idx + block_size] = cc.ravel()
        S_vals[idx : idx + block_size] = (S_exact - S_smooth).ravel()
        D_vals[idx : idx + block_size] = (D_exact - D_smooth).ravel()
        idx += block_size

    S_corr_csr = csr_matrix(
        (S_vals[:idx], (rows_arr[:idx], cols_arr[:idx])),
        shape=(n_bdry, n_bdry),
    )
    D_corr_csr = csr_matrix(
        (D_vals[:idx], (rows_arr[:idx], cols_arr[:idx])),
        shape=(n_bdry, n_bdry),
    )

    return dict(
        S_corr=S_corr_csr,
        D_corr=D_corr_csr,
        n_near_pairs=len(near_pairs),
        n_patches=n_patches,
        nnz_S=S_corr_csr.nnz,
        nnz_D=D_corr_csr.nnz,
        kappa=kappa,
        fmm_eps=fmm_eps,
    )


def load_nearfield_correction(fp: str, fmm_eps: float = 1e-7) -> dict:
    """Load near-field correction from .npz (generated by gen_nearfield_3D.py).

    Returns a dict compatible with :func:`solve_bie_gmres_fmm`.
    """
    from scipy.sparse import csr_matrix

    d = np.load(fp, allow_pickle=False)
    shape = tuple(d["shape"])
    S_corr = csr_matrix(
        (d["S_corr_data"], d["S_corr_indices"], d["S_corr_indptr"]),
        shape=shape,
    )
    D_corr = csr_matrix(
        (d["D_corr_data"], d["D_corr_indices"], d["D_corr_indptr"]),
        shape=shape,
    )
    return dict(
        S_corr=S_corr,
        D_corr=D_corr,
        boundary_points=d["boundary_points"],
        normals=d["normals"],
        wts=d["wts"],
        n_near_pairs=int(d["n_near_pairs"]),
        nnz_S=S_corr.nnz,
        nnz_D=D_corr.nnz,
        kappa=float(d["kappa"]),
        fmm_eps=fmm_eps,
        a=float(d["a"]),
        q=int(d["q"]),
        L=int(d["L"]),
    )


def _fmm_apply_S(
    v: np.ndarray,
    bdry_pts: np.ndarray,
    wts: np.ndarray,
    kappa: float,
    eps: float,
) -> np.ndarray:
    """Apply single-layer operator via FMM: [Sv]_i = sum_{j!=i} G(x_i,x_j) w_j v_j."""
    import fmm3dpy

    src = np.asfortranarray(bdry_pts.T)  # (3, n)
    if v.ndim == 1:
        charges = (wts * v).astype(np.complex128)
        out = fmm3dpy.hfmm3d(
            eps=eps, zk=complex(kappa), sources=src, charges=charges, pg=1
        )
        return np.asarray(out.pot, dtype=np.complex128).ravel()
    # Batched: v is (n_bdry, n_rhs)
    n_rhs = v.shape[1]
    result = np.empty_like(v, dtype=np.complex128)
    for k in range(n_rhs):
        charges = (wts * v[:, k]).astype(np.complex128)
        out = fmm3dpy.hfmm3d(
            eps=eps, zk=complex(kappa), sources=src, charges=charges, pg=1
        )
        result[:, k] = np.asarray(out.pot, dtype=np.complex128).ravel()
    return result


def _fmm_apply_D(
    v: np.ndarray,
    bdry_pts: np.ndarray,
    normals: np.ndarray,
    wts: np.ndarray,
    kappa: float,
    eps: float,
) -> np.ndarray:
    """Apply double-layer operator via FMM: [Dv]_i = sum_{j!=i} dG/dn_y(x_i,x_j) w_j v_j.

    fmm3dpy evaluates  u(x) = sum_j -v_j . grad_x G(x, x_j).  Setting
    v_j = n_j w_j sigma_j yields the double-layer potential because
    -n_j . grad_x G = n_j . grad_y G = dG/dn_y.
    """
    import fmm3dpy

    src = np.asfortranarray(bdry_pts.T)  # (3, n)
    nrm_T = normals.T  # (3, n)
    if v.ndim == 1:
        scale = (wts * v).astype(np.complex128)  # (n,)
        dipvec = np.asfortranarray(nrm_T * scale[None, :])  # (3, n)
        out = fmm3dpy.hfmm3d(
            eps=eps, zk=complex(kappa), sources=src, dipvec=dipvec, pg=1
        )
        return np.asarray(out.pot, dtype=np.complex128).ravel()
    n_rhs = v.shape[1]
    result = np.empty_like(v, dtype=np.complex128)
    for k in range(n_rhs):
        scale = (wts * v[:, k]).astype(np.complex128)
        dipvec = np.asfortranarray(nrm_T * scale[None, :])
        out = fmm3dpy.hfmm3d(
            eps=eps, zk=complex(kappa), sources=src, dipvec=dipvec, pg=1
        )
        result[:, k] = np.asarray(out.pot, dtype=np.complex128).ravel()
    return result


def fmm_matvec_S(
    v: np.ndarray,
    bdry_pts: np.ndarray,
    wts: np.ndarray,
    kappa: float,
    S_corr,
    fmm_eps: float = 1e-7,
) -> np.ndarray:
    """FMM-accelerated single-layer matvec: S @ v = FMM(v) + S_corr @ v."""
    fmm_part = _fmm_apply_S(v, bdry_pts, wts, kappa, fmm_eps)
    if v.ndim == 1:
        return fmm_part + S_corr @ v
    return fmm_part + S_corr @ v


def fmm_matvec_D(
    v: np.ndarray,
    bdry_pts: np.ndarray,
    normals: np.ndarray,
    wts: np.ndarray,
    kappa: float,
    D_corr,
    fmm_eps: float = 1e-7,
) -> np.ndarray:
    """FMM-accelerated double-layer matvec: D @ v = FMM(v) + D_corr @ v."""
    fmm_part = _fmm_apply_D(v, bdry_pts, normals, wts, kappa, fmm_eps)
    if v.ndim == 1:
        return fmm_part + D_corr @ v
    return fmm_part + D_corr @ v


def solve_bie_gmres_fmm(
    T_DtN,
    bdry_pts: np.ndarray,
    normals: np.ndarray,
    wts: np.ndarray,
    kappa: float,
    eta: float,
    uin: np.ndarray,
    uin_dn: np.ndarray,
    nf_corr: dict,
    tol: float = 1e-6,
    maxiter: int = 200,
    restart: int = 50,
    use_gpu_tdtn: bool = False,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
    """Solve the exterior BIE via GMRES with FMM-accelerated matvecs.

    Solves ``A u^s = b`` where ``A = 1/2 I - D + S T_DtN`` and
    ``b = S (u^inc_n - T_DtN u^inc)`` using GMRES with FMM for S, D.

    When ``use_gpu_tdtn=True``, the dense ``T_DtN @ v`` products are
    dispatched to the GPU via JAX while FMM calls run concurrently on
    CPU.  The GPU launch is asynchronous, so ``T_DtN @ x`` and
    ``FMM_D(x)`` overlap within each GMRES iteration.

    Returns ``(imp, uscat_b, uscat_dn_b, info)`` matching the dense solver.
    """
    from scipy.sparse.linalg import LinearOperator, gmres

    S_corr = nf_corr["S_corr"]
    D_corr = nf_corr["D_corr"]
    fmm_eps = nf_corr["fmm_eps"]
    n = bdry_pts.shape[0]

    # ---- T_DtN matmul dispatch (GPU or CPU) ----
    if use_gpu_tdtn:
        T_gpu = jnp.asarray(T_DtN)
        jax.block_until_ready(T_gpu)

        def _tdtn_mv(v_np):
            """T_DtN @ v on GPU; returns np.ndarray."""
            result = T_gpu @ jax.device_put(jnp.asarray(v_np))
            return np.asarray(result)

        def _tdtn_mv_async(v_np):
            """Launch T_DtN @ v on GPU; return a lazy JAX array (not blocked)."""
            return T_gpu @ jax.device_put(jnp.asarray(v_np))

        def _collect(jax_arr):
            """Block + transfer a lazy JAX result to numpy."""
            return np.asarray(jax_arr)

    else:
        T_cpu = np.asarray(T_DtN)

        def _tdtn_mv(v_np):
            return T_cpu @ v_np

        def _tdtn_mv_async(v_np):
            return T_cpu @ v_np

        def _collect(arr):
            return arr

    def _apply_S(v):
        return fmm_matvec_S(v, bdry_pts, wts, kappa, S_corr, fmm_eps)

    def _apply_D(v):
        return fmm_matvec_D(v, bdry_pts, normals, wts, kappa, D_corr, fmm_eps)

    def matvec(x):
        # T_DtN @ x on GPU (async) while FMM_D runs on CPU
        Tx_lazy = _tdtn_mv_async(x)
        Dx = _apply_D(x)
        Tx = _collect(Tx_lazy)
        return 0.5 * x - Dx + _apply_S(Tx)

    A_op = LinearOperator((n, n), matvec=matvec, dtype=np.complex128)

    # RHS: b = S @ (uin_dn - T_DtN @ uin)
    uin_np = np.asarray(uin)
    uin_dn_np = np.asarray(uin_dn)

    n_src = uin_np.shape[1] if uin_np.ndim > 1 else 1
    if uin_np.ndim == 1:
        uin_np = uin_np[:, None]
        uin_dn_np = uin_dn_np[:, None]

    uscat_b_cols = []
    gmres_info_list = []
    for s in range(n_src):
        rhs_s = _apply_S(uin_dn_np[:, s] - _tdtn_mv(uin_np[:, s]))
        sol, info_code = gmres(
            A_op, rhs_s, rtol=tol, restart=restart, maxiter=maxiter, atol=0
        )
        uscat_b_cols.append(sol)
        gmres_info_list.append(info_code)

    uscat_b = np.column_stack(uscat_b_cols)
    uscat_dn_b = _tdtn_mv(uscat_b + uin_np) - uin_dn_np
    imp = uscat_dn_b + 1j * eta * uscat_b

    info = dict(
        gmres_info=gmres_info_list,
        n_src=n_src,
        converged=all(c == 0 for c in gmres_info_list),
    )
    return imp, uscat_b, uscat_dn_b, info


def solve_bie_gmres_gpu(
    T_DtN,
    bdry_pts: np.ndarray,
    normals: np.ndarray,
    wts: np.ndarray,
    kappa: float,
    eta: float,
    uin: np.ndarray,
    uin_dn: np.ndarray,
    nf_corr: dict,
    tol: float = 1e-6,
    maxiter: int = 200,
    restart: int = 50,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
    """Solve the exterior BIE entirely on GPU via JAX direct summation.

    Replaces the CPU-side FMM with GPU kernel evaluation.  The smooth
    Helmholtz kernels :math:`G` and :math:`\\partial G/\\partial n_y` are
    built once as dense :math:`n \\times n` matrices on the GPU, the
    near-field corrections are added, and each GMRES iteration reduces to
    three GPU GEMVs (:math:`T \\cdot x`, :math:`D \\cdot x`, :math:`S \\cdot Tx`).

    Memory: :math:`3n^2 \\times 16` bytes for the stored matrices
    (S + D + T).  At :math:`n = 24{,}576` (L = 3) this is ~29 GB —
    fits on an 80 GB GPU.

    Returns ``(imp, uscat_b, uscat_dn_b, info)`` matching the dense solver.
    """
    from scipy.sparse.linalg import LinearOperator, gmres

    n = bdry_pts.shape[0]

    # ---- Build smooth kernel matrices on GPU ----
    t0 = time.perf_counter()
    bp = jnp.asarray(bdry_pts)
    nrm = jnp.asarray(normals)
    w = jnp.asarray(wts)
    T = jnp.asarray(T_DtN)

    diff = bp[:, None, :] - bp[None, :, :]  # (n, n, 3)
    r2 = jnp.sum(diff**2, axis=-1)  # (n, n)
    r = jnp.sqrt(r2)
    safe_r = jnp.where(r > 0, r, 1.0)

    # S kernel: G(x_i, x_j) * w_j
    G = jnp.exp(1j * kappa * r) / (4.0 * jnp.pi * safe_r)
    G = jnp.where(r > 0, G, 0j)
    K_S = G * w[None, :]

    # D kernel: dG/dn_y * w_j
    nd = jnp.sum(diff * nrm[None, :, :], axis=-1)
    dGdn = (1.0 / safe_r - 1j * kappa) / safe_r * G * nd
    dGdn = jnp.where(r > 0, dGdn, 0j)
    K_D = dGdn * w[None, :]

    del diff, r2, r, safe_r, G, nd, dGdn

    # Add near-field corrections (exact quadrature minus smooth kernel)
    K_S = K_S + jnp.asarray(nf_corr["S_corr"].toarray())
    K_D = K_D + jnp.asarray(nf_corr["D_corr"].toarray())

    jax.block_until_ready(K_S)
    jax.block_until_ready(K_D)
    dt_build = time.perf_counter() - t0
    print(f"  GPU kernel build: {dt_build:.2f}s")
    mem_gb = (K_S.nbytes + K_D.nbytes + T.nbytes) / 1e9
    print(f"  K_S + K_D + T memory: {mem_gb:.2f} GB")

    # ---- JIT-compiled matvec: A x = 1/2 x - D x + S (T x) ----
    @jax.jit
    def _matvec(x):
        return 0.5 * x - K_D @ x + K_S @ (T @ x)

    # Warm up JIT
    _dummy = _matvec(jnp.zeros(n, dtype=jnp.complex128))
    jax.block_until_ready(_dummy)
    del _dummy

    def matvec_np(x_np):
        return np.array(_matvec(jnp.asarray(x_np)))  # writable copy

    A_op = LinearOperator((n, n), matvec=matvec_np, dtype=np.complex128)

    # ---- RHS and GMRES solve ----
    uin_np = np.asarray(uin)
    uin_dn_np = np.asarray(uin_dn)
    n_src = uin_np.shape[1] if uin_np.ndim > 1 else 1
    if uin_np.ndim == 1:
        uin_np = uin_np[:, None]
        uin_dn_np = uin_dn_np[:, None]

    uscat_b_cols = []
    gmres_info_list = []
    for s in range(n_src):
        u_s = jnp.asarray(uin_np[:, s])
        udn_s = jnp.asarray(uin_dn_np[:, s])
        rhs_j = K_S @ (udn_s - T @ u_s)
        rhs_np = np.array(rhs_j)  # writable copy for scipy
        sol, info_code = gmres(
            A_op, rhs_np, rtol=tol, restart=restart, maxiter=maxiter, atol=0
        )
        uscat_b_cols.append(sol)
        gmres_info_list.append(info_code)

    uscat_b = np.column_stack(uscat_b_cols)
    uscat_dn_b = np.array(
        T @ jnp.asarray(uscat_b + uin_np) - jnp.asarray(uin_dn_np)
    )
    imp = uscat_dn_b + 1j * eta * uscat_b

    info = dict(
        gmres_info=gmres_info_list,
        n_src=n_src,
        converged=all(c == 0 for c in gmres_info_list),
        kernel_build_time=dt_build,
    )
    return imp, uscat_b, uscat_dn_b, info


# ---------------------------------------------------------------------------
# BIE coupling -- 3D analogue of examples/wave_scattering_utils.py
# ---------------------------------------------------------------------------
#
# Convention (matches the HPS 3D ItI solver and the 2D wave-scattering utils):
#   g_in  = u_n + i*eta*u    (incoming impedance trace)
#   g_out = u_n - i*eta*u    (outgoing impedance trace)
#   R = T_ItI : g_in -> g_out
#
# From the two impedance equations,  u_n = T u  is recovered by Cayley:
#   T_DtN = -i*eta * (R - I)^{-1} (R + I).
#
# Exterior BIE for the scattered field (Gillman-Barnett-Martinsson eq. 3.4):
#   A u^s = b,   A = (1/2) I - D + S T_int,   b = S (u^inc_n - T_int u^inc),
# where D here is the principal-value double-layer (no jump baked in) and
# n is the outward normal of the cube.  After solving for u^s on the boundary,
# the scattered normal trace and the incoming impedance for the down-pass are
#   u^s_n = T_int (u^s + u^inc) - u^inc_n,
#   g_in^s = u^s_n + i*eta*u^s,
# and the off-surface representation is u^s(x) = D[u^s](x) - S[u^s_n](x).


@jax.jit
def get_DtN_from_ItI_3D(R: jnp.ndarray, eta: float) -> jnp.ndarray:
    """Cayley transform from the 3D ItI map to the matching DtN map.

    Implements ``T = -i*eta * (R - I)^{-1} (R + I)`` -- same convention as
    :func:`wave_scattering_utils.get_DtN_from_ItI` in 2D.
    """
    n = R.shape[0]
    I = jnp.eye(n, dtype=R.dtype)
    return -1j * eta * jnp.linalg.solve(R - I, R + I)


@jax.jit
def get_uin_and_dn_3D(
    k: float,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    source_dirs: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Evaluate plane-wave incident traces and normal derivatives on ``bdry_pts``.

    ``u^inc(x) = exp(i k w . x)``,
    ``d u^inc / dn = i k (w . n) u^inc(x)``.

    Args:
        k:            wavenumber.
        bdry_pts:     ``(n_bdry, 3)`` boundary nodes.
        normals:      ``(n_bdry, 3)`` outward unit normals at the boundary nodes.
        source_dirs:  ``(n_src, 3)`` incident unit direction vectors.

    Returns:
        ``uin`` and ``uin_dn`` each of shape ``(n_bdry, n_src)``.
    """
    phases = bdry_pts @ source_dirs.T
    uin = jnp.exp(1j * k * phases)
    wn = normals @ source_dirs.T
    uin_dn = 1j * k * wn * uin
    return uin, uin_dn


@jax.jit
def get_uin_and_dn_pointsource_3D(
    k: float,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    src_pts: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Point-source incident traces and normal derivatives on ``bdry_pts``.

    ``u^inc(x) = exp(i k |x - s|) / (4 pi |x - s|)`` (3D free-space Green's
    function), so

    ``d u^inc / dn = (i k - 1/r) ((x - s) . n / r) u^inc(x)``.

    Args:
        k:         wavenumber.
        bdry_pts:  ``(n_bdry, 3)`` boundary nodes.
        normals:   ``(n_bdry, 3)`` outward unit normals at the boundary nodes.
        src_pts:   ``(n_src, 3)`` point-source locations (outside the cube).

    Returns:
        ``uin`` and ``uin_dn`` each of shape ``(n_bdry, n_src)``.
    """
    diff = bdry_pts[:, None, :] - src_pts[None, :, :]  # (n_bdry, n_src, 3)
    r = jnp.linalg.norm(diff, axis=-1)
    uin = jnp.exp(1j * k * r) / (4.0 * jnp.pi * r)
    n_dot_diff = jnp.einsum("bj,bsj->bs", normals, diff)
    uin_dn = (1j * k - 1.0 / r) * (n_dot_diff / r) * uin
    return uin, uin_dn


@jax.jit
def setup_scattering_lin_system_3D(
    S: jnp.ndarray,
    D: jnp.ndarray,
    T_int: jnp.ndarray,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    k: float,
    source_dirs: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Assemble ``A`` and ``b`` for the exterior BIE coupling.

    Returns
    -------
    A : ``(n_bdry, n_bdry)`` complex matrix  ``= (1/2) I - D + S T_int``.
    b : ``(n_bdry, n_src)`` right-hand side  ``= S (u^inc_n - T_int u^inc)``.
    """
    n = bdry_pts.shape[0]
    uin, uin_dn = get_uin_and_dn_3D(k, bdry_pts, normals, source_dirs)
    A = 0.5 * jnp.eye(n, dtype=S.dtype) - D + S @ T_int
    b = S @ (uin_dn - T_int @ uin)
    return A, b


@jax.jit
def get_scattering_uscat_impedance_3D(
    S: jnp.ndarray,
    D: jnp.ndarray,
    T_DtN: jnp.ndarray,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    k: float,
    eta: float,
    source_dirs: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray]:
    """Solve the BIE, recover the scattered Dirichlet + Neumann + impedance traces.

    Returns
    -------
    imp        : ``(n_bdry, n_src)``  incoming impedance ``u^s_n + i*eta*u^s``.
    uscat_b    : ``(n_bdry, n_src)``  scattered Dirichlet trace ``u^s``.
    uscat_dn_b : ``(n_bdry, n_src)``  scattered Neumann trace  ``u^s_n``.
    """
    A, rhs = setup_scattering_lin_system_3D(
        S, D, T_DtN, bdry_pts, normals, k, source_dirs
    )
    uin, uin_dn = get_uin_and_dn_3D(k, bdry_pts, normals, source_dirs)
    uscat_b = jnp.linalg.solve(A, rhs)
    uscat_dn_b = T_DtN @ (uscat_b + uin) - uin_dn
    imp = uscat_dn_b + 1j * eta * uscat_b
    return imp, uscat_b, uscat_dn_b


@jax.jit
def get_scattering_uscat_impedance_from_traces_3D(
    S: jnp.ndarray,
    D: jnp.ndarray,
    T_DtN: jnp.ndarray,
    uin: jnp.ndarray,
    uin_dn: jnp.ndarray,
    eta: float,
) -> Tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray]:
    """Same BIE solve as :func:`get_scattering_uscat_impedance_3D` but for
    precomputed incident traces (e.g. from point sources).

    Args:
        S, D:     ``(n_bdry, n_bdry)`` single/double-layer matrices.
        T_DtN:    ``(n_bdry, n_bdry)`` interior DtN map.
        uin:      ``(n_bdry, n_src)`` incident Dirichlet trace.
        uin_dn:   ``(n_bdry, n_src)`` incident Neumann trace.
        eta:      ItI impedance parameter.

    Returns ``(imp, uscat_b, uscat_dn_b)``, each ``(n_bdry, n_src)``.
    """
    n = uin.shape[0]
    A = 0.5 * jnp.eye(n, dtype=S.dtype) - D + S @ T_DtN
    rhs = S @ (uin_dn - T_DtN @ uin)
    uscat_b = jnp.linalg.solve(A, rhs)
    uscat_dn_b = T_DtN @ (uscat_b + uin) - uin_dn
    imp = uscat_dn_b + 1j * eta * uscat_b
    return imp, uscat_b, uscat_dn_b


@jax.jit
def eval_uscat_offsurface_3D(
    target_pts: jnp.ndarray,
    src_pts: jnp.ndarray,
    src_normals: jnp.ndarray,
    src_weights: jnp.ndarray,
    uscat_b: jnp.ndarray,
    uscat_dn_b: jnp.ndarray,
    k: float,
) -> jnp.ndarray:
    """Evaluate the scattered field at off-surface targets via the exterior rep.

    ``u^s(x) = D[u^s](x) - S[u^s_n](x)`` for ``x`` strictly outside the cube.
    Smooth Gauss-Legendre quadrature -- accuracy degrades for ``x`` within an
    inter-node spacing of the surface (no local correction is applied here).
    With ``q`` nodes per direction per face, the rule of thumb is to keep
    ``dist(x, dOmega) >= a/q``.

    Args:
        target_pts:     ``(n_t, 3)`` target points outside the cube.
        src_pts:        ``(n_s, 3)`` boundary quadrature nodes.
        src_normals:    ``(n_s, 3)`` outward normals at the source nodes.
        src_weights:    ``(n_s,)``   quadrature weights.
        uscat_b:        ``(n_s,)`` or ``(n_s, n_src)`` scattered Dirichlet trace.
        uscat_dn_b:     ``(n_s,)`` or ``(n_s, n_src)`` scattered Neumann trace.
        k:              wavenumber.

    Returns:
        ``u^s`` at ``target_pts``; shape ``(n_t,)`` or ``(n_t, n_src)`` mirroring
        the input trace shape.
    """
    diff = target_pts[:, None, :] - src_pts[None, :, :]
    r = jnp.linalg.norm(diff, axis=-1)
    G = jnp.exp(1j * k * r) / (4.0 * jnp.pi * r)
    # d_{n_y} G  where  diff = x - y  =>  d/dy_i = (1/r - i k) (diff_i / r) G.
    n_dot_diff = jnp.einsum("sj,tsj->ts", src_normals, diff)
    dG_dny = (1.0 / r - 1j * k) / r * G * n_dot_diff

    w_G = G * src_weights[None, :]
    w_dG = dG_dny * src_weights[None, :]
    return w_dG @ uscat_b - w_G @ uscat_dn_b


def solve_scattering_bie_3D(
    sd: dict,
    b_radial: Callable[[np.ndarray], np.ndarray],
    source_dirs: np.ndarray,
    eta: float = None,
    p: int = None,
) -> dict:
    """Set up the interior problem and solve the coupled exterior BIE.

    Performs the full HPS+BIE coupling up to (but not including) the interior
    down-pass:

    1. Builds a ``Domain``/``PDEProblem`` matching the ``(a, q, L, kappa)``
       metadata in ``sd``.  The scattered field satisfies
       ``Lap u^s + kappa^2 (1 - b) u^s = kappa^2 b u^inc``, so the source is
       evaluated per incident direction.
    2. Permutes the (S, D) matrices to the Domain's boundary ordering and
       cross-checks the stored normals against face-identified ones.
    3. Builds the HPS solver, Cayley-transforms the top-level ItI map to DtN.
    4. Solves the exterior BIE for the scattered traces and impedance.

    Args:
        sd:           dict from :func:`load_SD_matrices_3D`.
        b_radial:     radial scattering potential; called as ``b_radial(r)``
                      on arrays of radii.
        source_dirs:  ``(n_src, 3)`` incident unit directions.
        eta:          ItI impedance parameter; defaults to ``kappa``.
        p:            interior Chebyshev order; defaults to ``q + 4``.
                      The exterior-field error is dominated by the interior
                      solve (and its Neumann trace) rather than the boundary
                      quadrature, so the default keeps the interior order
                      ahead of ``q``; ``q + 4`` puts the interior error at
                      or below the boundary-quadrature error in measured
                      sweeps over q = 4..8 and L = 1..3.

    Returns a dict with:
        ``problem``           the PDEProblem (solver built; pass ``imp`` to
                              ``jaxhps.solve`` for the interior field),
        ``boundary_points``   ``(n_bdry, 3)`` in the Domain's ordering,
        ``normals``           ``(n_bdry, 3)`` outward normals,
        ``sdp``               the permuted SD dict (for quadrature weights),
        ``imp``               ``(n_bdry, n_src)`` scattered incoming impedance,
        ``uscat_b``           ``(n_bdry, n_src)`` scattered Dirichlet trace,
        ``uscat_dn_b``        ``(n_bdry, n_src)`` scattered Neumann trace.
    """
    a, q, L, kappa = sd["a"], sd["q"], sd["L"], sd["kappa"]
    eta = float(kappa if eta is None else eta)
    p = q + 4 if p is None else p
    source_dirs = np.asarray(source_dirs, dtype=np.float64)

    root = DiscretizationNode3D(
        xmin=-a, xmax=a, ymin=-a, ymax=a, zmin=-a, zmax=a
    )
    domain = Domain(p=p, q=q, root=root, L=L)

    int_pts = np.asarray(domain.interior_points)  # (n_leaves, p^3, 3)
    b_int = b_radial(np.linalg.norm(int_pts, axis=-1))
    I_coeffs = (kappa**2 * (1.0 - b_int)).astype(np.complex128)
    phases = np.einsum("lpd,sd->lps", int_pts, source_dirs)
    uin_int = np.exp(1j * kappa * phases)  # (n_leaves, p^3, n_src)
    src = (kappa**2 * b_int[..., None] * uin_int).astype(np.complex128)

    ones = np.ones_like(I_coeffs)
    problem = PDEProblem(
        domain=domain,
        D_xx_coefficients=ones,
        D_yy_coefficients=ones,
        D_zz_coefficients=ones,
        I_coefficients=I_coeffs,
        source=src,
        use_ItI=True,
        eta=eta,
    )

    bp = np.asarray(domain.boundary_points).reshape(-1, 3)
    _, sdp = permute_to_domain(sd, bp)
    nrm = outward_normals_for_cube_boundary(bp, root)
    if not np.allclose(sdp["normals"], nrm):
        bad = float(np.linalg.norm(sdp["normals"] - nrm, axis=-1).max())
        raise RuntimeError(
            f"normals don't agree after permutation: max diff {bad:.2e}"
        )

    T_ItI = build_solver(problem, return_top_T=True)
    T_DtN = get_DtN_from_ItI_3D(jnp.asarray(T_ItI), eta)

    imp, uscat_b, uscat_dn_b = get_scattering_uscat_impedance_3D(
        S=jnp.asarray(sdp["S"]),
        D=jnp.asarray(sdp["D"]),
        T_DtN=T_DtN,
        bdry_pts=jnp.asarray(bp),
        normals=jnp.asarray(nrm),
        k=float(kappa),
        eta=eta,
        source_dirs=jnp.asarray(source_dirs),
    )
    return dict(
        problem=problem,
        boundary_points=bp,
        normals=nrm,
        sdp=sdp,
        imp=imp,
        uscat_b=np.asarray(uscat_b),
        uscat_dn_b=np.asarray(uscat_dn_b),
    )


def build_cartesian_ctx(
    sd: dict,
    source_dirs: np.ndarray,
    eta: float = None,
    p: int = None,
) -> dict:
    """Precompute the ``b``-independent pieces shared by every solve.

    The discretization ``Domain``, the boundary-point permutation of the
    SD matrices, the outward normals, and the device-resident copies of
    ``S``, ``D``, the boundary points/normals and source directions depend
    only on ``(sd, source_dirs, p)`` -- not on the scattering potential.
    Building them once and reusing the returned ``ctx`` across many samples
    (see :func:`solve_scattering_bie_3D_cartesian`) removes the per-sample
    k-d tree permutation (~2 s) and the 1.2 GB host->device copy of ``S, D``.
    """
    a, q, L, kappa = sd["a"], sd["q"], sd["L"], sd["kappa"]
    eta = float(kappa if eta is None else eta)
    p = q + 4 if p is None else p
    source_dirs = np.asarray(source_dirs, dtype=np.float64)
    dev = jax.devices()[0]

    root = DiscretizationNode3D(
        xmin=-a, xmax=a, ymin=-a, ymax=a, zmin=-a, zmax=a
    )
    domain = Domain(p=p, q=q, root=root, L=L)
    int_pts = np.asarray(domain.interior_points)  # (n_leaves, p^3, 3)
    bp = np.asarray(domain.boundary_points).reshape(-1, 3)
    _, sdp = permute_to_domain(sd, bp)
    nrm = outward_normals_for_cube_boundary(bp, root)
    if not np.allclose(sdp["normals"], nrm):
        bad = float(np.linalg.norm(sdp["normals"] - nrm, axis=-1).max())
        raise RuntimeError(
            f"normals don't agree after permutation: max diff {bad:.2e}"
        )
    return dict(
        eta=eta,
        kappa=float(kappa),
        domain=domain,
        int_pts=int_pts,
        bp=bp,
        sdp=sdp,
        nrm=nrm,
        source_dirs=source_dirs,
        dev_S=jax.device_put(jnp.asarray(sdp["S"]), dev),
        dev_D=jax.device_put(jnp.asarray(sdp["D"]), dev),
        dev_bp=jax.device_put(jnp.asarray(bp), dev),
        dev_nrm=jax.device_put(jnp.asarray(nrm), dev),
        dev_src=jax.device_put(jnp.asarray(source_dirs), dev),
    )


def solve_scattering_bie_3D_cartesian(
    sd: dict,
    b_cartesian: Callable[[np.ndarray], np.ndarray],
    source_dirs: np.ndarray,
    eta: float = None,
    p: int = None,
    ctx: dict = None,
) -> dict:
    """Plane-wave variant of :func:`solve_scattering_bie_3D` with a cartesian ``b``.

    Identical HPS+BIE coupling and plane-wave incidence as
    :func:`solve_scattering_bie_3D`, but the scattering potential is an
    arbitrary (smooth) cartesian function ``b_cartesian(pts)`` evaluated on
    ``(..., 3)`` arrays rather than a radial profile.  Use this for
    off-center or multi-bump scatterers.

    ``ctx`` is an optional cache from :func:`build_cartesian_ctx`; when reused
    across many samples it amortizes the ``b``-independent setup.  If omitted,
    it is built on the fly (one-shot behaviour, unchanged results).

    Returns the same dict as :func:`solve_scattering_bie_3D`.
    """
    if ctx is None:
        ctx = build_cartesian_ctx(sd, source_dirs, eta=eta, p=p)
    eta = ctx["eta"]
    kappa = ctx["kappa"]
    domain = ctx["domain"]
    int_pts = ctx["int_pts"]
    bp = ctx["bp"]
    sdp = ctx["sdp"]
    nrm = ctx["nrm"]
    source_dirs = ctx["source_dirs"]
    dev = jax.devices()[0]

    t0 = _tic()
    b_int = b_cartesian(int_pts)
    I_coeffs = (kappa**2 * (1.0 - b_int)).astype(np.complex128)
    phases = np.einsum("lpd,sd->lps", int_pts, source_dirs)
    uin_int = np.exp(1j * kappa * phases)  # (n_leaves, p^3, n_src)
    src = (kappa**2 * b_int[..., None] * uin_int).astype(np.complex128)

    ones = np.ones_like(I_coeffs)
    problem = PDEProblem(
        domain=domain,
        D_xx_coefficients=ones,
        D_yy_coefficients=ones,
        D_zz_coefficients=ones,
        I_coefficients=I_coeffs,
        source=src,
        use_ItI=True,
        eta=eta,
    )
    t0 = _toc("PDEProblem", t0)

    # ``build_solver`` stores its outputs on ``host_device`` (CPU by default),
    # so the returned ItI map lands on CPU.  Move it to the compute device so
    # the Cayley transform and BIE solve below run there (a ~50x speedup on GPU).
    T_ItI = build_solver(problem, return_top_T=True)
    R = jax.device_put(jnp.asarray(T_ItI), dev)
    jax.block_until_ready(R)
    t0 = _toc("build_solver", t0)
    T_DtN = get_DtN_from_ItI_3D(R, eta)
    jax.block_until_ready(T_DtN)
    t0 = _toc("get_DtN_from_ItI", t0)

    imp, uscat_b, uscat_dn_b = get_scattering_uscat_impedance_3D(
        S=ctx["dev_S"],
        D=ctx["dev_D"],
        T_DtN=T_DtN,
        bdry_pts=ctx["dev_bp"],
        normals=ctx["dev_nrm"],
        k=kappa,
        eta=eta,
        source_dirs=ctx["dev_src"],
    )
    jax.block_until_ready(uscat_b)
    t0 = _toc("get_scattering_uscat_impedance", t0)
    return dict(
        problem=problem,
        boundary_points=bp,
        normals=nrm,
        sdp=sdp,
        imp=imp,
        uscat_b=np.asarray(uscat_b),
        uscat_dn_b=np.asarray(uscat_dn_b),
    )


def solve_scattering_bie_3D_pointsource(
    sd: dict,
    b_cartesian: Callable[[np.ndarray], np.ndarray],
    src_pts: np.ndarray,
    eta: float = None,
    p: int = None,
) -> dict:
    """Point-source variant of :func:`solve_scattering_bie_3D`.

    Identical HPS+BIE coupling, with two generalizations:

    * the scattering potential is an arbitrary (smooth) cartesian function
      ``b_cartesian(pts)`` evaluated on ``(..., 3)`` arrays, rather than a
      radial profile;
    * the incident field is a point source ``exp(i k |x - s|) / (4 pi |x - s|)``
      for each row ``s`` of ``src_pts`` (all sources must lie strictly outside
      the cube), rather than a plane wave.

    Returns the same dict as :func:`solve_scattering_bie_3D`.
    """
    a, q, L, kappa = sd["a"], sd["q"], sd["L"], sd["kappa"]
    eta = float(kappa if eta is None else eta)
    p = q + 2 if p is None else p
    src_pts = np.asarray(src_pts, dtype=np.float64)
    if np.max(np.abs(src_pts)) <= a:
        raise ValueError(
            "all point sources must lie strictly outside the cube"
        )

    root = DiscretizationNode3D(
        xmin=-a, xmax=a, ymin=-a, ymax=a, zmin=-a, zmax=a
    )
    domain = Domain(p=p, q=q, root=root, L=L)

    int_pts = np.asarray(domain.interior_points)  # (n_leaves, p^3, 3)
    b_int = b_cartesian(int_pts)
    I_coeffs = (kappa**2 * (1.0 - b_int)).astype(np.complex128)
    diff = int_pts[:, :, None, :] - src_pts[None, None, :, :]
    r = np.linalg.norm(diff, axis=-1)  # (n_leaves, p^3, n_src)
    uin_int = np.exp(1j * kappa * r) / (4.0 * np.pi * r)
    src = (kappa**2 * b_int[..., None] * uin_int).astype(np.complex128)

    ones = np.ones_like(I_coeffs)
    problem = PDEProblem(
        domain=domain,
        D_xx_coefficients=ones,
        D_yy_coefficients=ones,
        D_zz_coefficients=ones,
        I_coefficients=I_coeffs,
        source=src,
        use_ItI=True,
        eta=eta,
    )

    bp = np.asarray(domain.boundary_points).reshape(-1, 3)
    _, sdp = permute_to_domain(sd, bp)
    nrm = outward_normals_for_cube_boundary(bp, root)
    if not np.allclose(sdp["normals"], nrm):
        bad = float(np.linalg.norm(sdp["normals"] - nrm, axis=-1).max())
        raise RuntimeError(
            f"normals don't agree after permutation: max diff {bad:.2e}"
        )

    T_ItI = build_solver(problem, return_top_T=True)
    T_DtN = get_DtN_from_ItI_3D(jnp.asarray(T_ItI), eta)

    uin, uin_dn = get_uin_and_dn_pointsource_3D(
        float(kappa), jnp.asarray(bp), jnp.asarray(nrm), jnp.asarray(src_pts)
    )
    imp, uscat_b, uscat_dn_b = get_scattering_uscat_impedance_from_traces_3D(
        S=jnp.asarray(sdp["S"]),
        D=jnp.asarray(sdp["D"]),
        T_DtN=T_DtN,
        uin=uin,
        uin_dn=uin_dn,
        eta=eta,
    )
    return dict(
        problem=problem,
        boundary_points=bp,
        normals=nrm,
        sdp=sdp,
        imp=imp,
        uscat_b=np.asarray(uscat_b),
        uscat_dn_b=np.asarray(uscat_dn_b),
    )
