"""Loader for 3D Helmholtz single/double-layer matrices generated by gen_SD_3D.py.

The 3D analog of ``wave_scattering_utils.load_SD_matrices`` for 2D.  The 2D
matrices come from a MATLAB chunkIE driver and are shipped as ``.mat`` files;
the 3D matrices come from ``examples/gen_SD_3D.py`` (which uses fmm3dbie under
the hood) and are shipped as ``.npz``.

The matrices are stored in fmm3dbie's natural node ordering (faces in order
xmin, xmax, ymin, ymax, zmin, zmax, each face flattened with row-major
``indexing="xy"`` over tensor-product GL nodes).  This generally does NOT
match the order produced by ``Domain.boundary_points``, which uses
``indexing="ij"`` and has a different per-face axis convention forced by the
outward-normal requirement of fmm3dbie's quad patches.  The
``permute_to_domain`` helper computes the permutation between the two by
matching 3D positions, so callers can work entirely in the domain's ordering.
"""

import numpy as np
import jax
import jax.numpy as jnp
from typing import Callable, Tuple

from jaxhps import (
    DiscretizationNode3D,
    Domain,
    PDEProblem,
    build_solver,
)


def load_SD_matrices_3D(
    fp: str,
) -> dict:
    """Read the .npz produced by ``gen_SD_3D.py``.

    Returns a dict with the matrices and metadata; nothing is converted to JAX
    here because callers may want to permute before pushing to device.
    """
    d = np.load(fp, allow_pickle=False)
    out = dict(
        S=d["S"],
        D=d["D"],
        wts=d["wts"],
        boundary_points=d["boundary_points"],
        normals=d["normals"],
        face_idx=d["face_idx"],
        a=float(d["a"]),
        q=int(d["q"]),
        L=int(d["L"]),
        kappa=float(d["kappa"]),
        eps=float(d["eps"]),
    )
    return out


def permute_to_domain(
    sd_data: dict,
    domain_boundary_points: np.ndarray,
    atol: float = 1e-10,
) -> Tuple[np.ndarray, dict]:
    """Find the permutation ``P`` such that ``boundary_points[P] == domain_boundary_points``.

    Both node sets must be the same set of points; only the ordering differs.
    Internally uses an O(N log N) k-d tree lookup; raises if the nearest match
    for any domain point exceeds ``atol`` or if the resulting map is not a
    bijection (which would indicate an actual mismatch, not just a reordering).

    Returns ``(P, permuted)`` where ``permuted`` is a fresh dict mirroring
    ``sd_data`` with ``S, D, wts, boundary_points, normals, face_idx`` all
    reordered so row/column ``i`` corresponds to ``domain_boundary_points[i]``.
    """
    from scipy.spatial import cKDTree

    bp_src = np.asarray(sd_data["boundary_points"])
    bp_dst = np.asarray(domain_boundary_points)
    if bp_src.shape != bp_dst.shape:
        raise ValueError(
            f"boundary point set sizes differ: "
            f"npz has {bp_src.shape}, domain has {bp_dst.shape}.  "
            f"Did you generate the matrices for the matching (q, L, a)?"
        )

    tree = cKDTree(bp_src)
    dists, P = tree.query(bp_dst, k=1)
    max_d = float(np.max(dists))
    if max_d > atol:
        raise ValueError(
            f"could not match domain boundary points to the npz set: "
            f"max nearest-neighbor distance {max_d:.3e} > atol={atol:.1e}.  "
            f"Likely cause: (a, q, L) mismatch between generation and Domain."
        )
    if len(set(P.tolist())) != len(P):
        raise ValueError(
            "node match was not a bijection -- duplicate sources mapped to "
            "the same domain target.  This should be impossible if the two "
            "point sets agree set-wise."
        )

    permuted = dict(sd_data)
    permuted["boundary_points"] = bp_src[P]
    permuted["normals"] = np.asarray(sd_data["normals"])[P]
    permuted["face_idx"] = np.asarray(sd_data["face_idx"])[P]
    permuted["wts"] = np.asarray(sd_data["wts"])[P]
    permuted["S"] = np.asarray(sd_data["S"])[np.ix_(P, P)]
    permuted["D"] = np.asarray(sd_data["D"])[np.ix_(P, P)]
    return P, permuted


def outward_normals_for_cube_boundary(
    boundary_points: np.ndarray, root
) -> np.ndarray:
    """Outward unit normals at the cube's boundary nodes, identified by face.

    ``root`` is any object with ``xmin .. zmax`` attributes (e.g. a
    ``DiscretizationNode3D``).
    """
    n = np.zeros_like(boundary_points)
    eps = 1e-9
    n[np.abs(boundary_points[:, 0] - root.xmin) < eps] = [-1, 0, 0]
    n[np.abs(boundary_points[:, 0] - root.xmax) < eps] = [1, 0, 0]
    n[np.abs(boundary_points[:, 1] - root.ymin) < eps] = [0, -1, 0]
    n[np.abs(boundary_points[:, 1] - root.ymax) < eps] = [0, 1, 0]
    n[np.abs(boundary_points[:, 2] - root.zmin) < eps] = [0, 0, -1]
    n[np.abs(boundary_points[:, 2] - root.zmax) < eps] = [0, 0, 1]
    return n


# ---------------------------------------------------------------------------
# BIE coupling -- 3D analogue of examples/wave_scattering_utils.py
# ---------------------------------------------------------------------------
#
# Convention (matches the HPS 3D ItI solver and the 2D wave-scattering utils):
#   g_in  = u_n + i*eta*u    (incoming impedance trace)
#   g_out = u_n - i*eta*u    (outgoing impedance trace)
#   R = T_ItI : g_in -> g_out
#
# From the two impedance equations,  u_n = T u  is recovered by Cayley:
#   T_DtN = -i*eta * (R - I)^{-1} (R + I).
#
# Exterior BIE for the scattered field (Gillman-Barnett-Martinsson eq. 3.4):
#   A u^s = b,   A = (1/2) I - D + S T_int,   b = S (u^inc_n - T_int u^inc),
# where D here is the principal-value double-layer (no jump baked in) and
# n is the outward normal of the cube.  After solving for u^s on the boundary,
# the scattered normal trace and the incoming impedance for the down-pass are
#   u^s_n = T_int (u^s + u^inc) - u^inc_n,
#   g_in^s = u^s_n + i*eta*u^s,
# and the off-surface representation is u^s(x) = D[u^s](x) - S[u^s_n](x).


@jax.jit
def get_DtN_from_ItI_3D(R: jnp.ndarray, eta: float) -> jnp.ndarray:
    """Cayley transform from the 3D ItI map to the matching DtN map.

    Implements ``T = -i*eta * (R - I)^{-1} (R + I)`` -- same convention as
    :func:`wave_scattering_utils.get_DtN_from_ItI` in 2D.
    """
    n = R.shape[0]
    I = jnp.eye(n, dtype=R.dtype)
    return -1j * eta * jnp.linalg.solve(R - I, R + I)


@jax.jit
def get_uin_and_dn_3D(
    k: float,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    source_dirs: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Evaluate plane-wave incident traces and normal derivatives on ``bdry_pts``.

    ``u^inc(x) = exp(i k w . x)``,
    ``d u^inc / dn = i k (w . n) u^inc(x)``.

    Args:
        k:            wavenumber.
        bdry_pts:     ``(n_bdry, 3)`` boundary nodes.
        normals:      ``(n_bdry, 3)`` outward unit normals at the boundary nodes.
        source_dirs:  ``(n_src, 3)`` incident unit direction vectors.

    Returns:
        ``uin`` and ``uin_dn`` each of shape ``(n_bdry, n_src)``.
    """
    phases = bdry_pts @ source_dirs.T
    uin = jnp.exp(1j * k * phases)
    wn = normals @ source_dirs.T
    uin_dn = 1j * k * wn * uin
    return uin, uin_dn


@jax.jit
def setup_scattering_lin_system_3D(
    S: jnp.ndarray,
    D: jnp.ndarray,
    T_int: jnp.ndarray,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    k: float,
    source_dirs: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """Assemble ``A`` and ``b`` for the exterior BIE coupling.

    Returns
    -------
    A : ``(n_bdry, n_bdry)`` complex matrix  ``= (1/2) I - D + S T_int``.
    b : ``(n_bdry, n_src)`` right-hand side  ``= S (u^inc_n - T_int u^inc)``.
    """
    n = bdry_pts.shape[0]
    uin, uin_dn = get_uin_and_dn_3D(k, bdry_pts, normals, source_dirs)
    A = 0.5 * jnp.eye(n, dtype=S.dtype) - D + S @ T_int
    b = S @ (uin_dn - T_int @ uin)
    return A, b


@jax.jit
def get_scattering_uscat_impedance_3D(
    S: jnp.ndarray,
    D: jnp.ndarray,
    T_DtN: jnp.ndarray,
    bdry_pts: jnp.ndarray,
    normals: jnp.ndarray,
    k: float,
    eta: float,
    source_dirs: jnp.ndarray,
) -> Tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray]:
    """Solve the BIE, recover the scattered Dirichlet + Neumann + impedance traces.

    Returns
    -------
    imp        : ``(n_bdry, n_src)``  incoming impedance ``u^s_n + i*eta*u^s``.
    uscat_b    : ``(n_bdry, n_src)``  scattered Dirichlet trace ``u^s``.
    uscat_dn_b : ``(n_bdry, n_src)``  scattered Neumann trace  ``u^s_n``.
    """
    A, rhs = setup_scattering_lin_system_3D(
        S, D, T_DtN, bdry_pts, normals, k, source_dirs
    )
    uin, uin_dn = get_uin_and_dn_3D(k, bdry_pts, normals, source_dirs)
    uscat_b = jnp.linalg.solve(A, rhs)
    uscat_dn_b = T_DtN @ (uscat_b + uin) - uin_dn
    imp = uscat_dn_b + 1j * eta * uscat_b
    return imp, uscat_b, uscat_dn_b


@jax.jit
def eval_uscat_offsurface_3D(
    target_pts: jnp.ndarray,
    src_pts: jnp.ndarray,
    src_normals: jnp.ndarray,
    src_weights: jnp.ndarray,
    uscat_b: jnp.ndarray,
    uscat_dn_b: jnp.ndarray,
    k: float,
) -> jnp.ndarray:
    """Evaluate the scattered field at off-surface targets via the exterior rep.

    ``u^s(x) = D[u^s](x) - S[u^s_n](x)`` for ``x`` strictly outside the cube.
    Smooth Gauss-Legendre quadrature -- accuracy degrades for ``x`` within an
    inter-node spacing of the surface (no local correction is applied here).
    With ``q`` nodes per direction per face, the rule of thumb is to keep
    ``dist(x, dOmega) >= a/q``.

    Args:
        target_pts:     ``(n_t, 3)`` target points outside the cube.
        src_pts:        ``(n_s, 3)`` boundary quadrature nodes.
        src_normals:    ``(n_s, 3)`` outward normals at the source nodes.
        src_weights:    ``(n_s,)``   quadrature weights.
        uscat_b:        ``(n_s,)`` or ``(n_s, n_src)`` scattered Dirichlet trace.
        uscat_dn_b:     ``(n_s,)`` or ``(n_s, n_src)`` scattered Neumann trace.
        k:              wavenumber.

    Returns:
        ``u^s`` at ``target_pts``; shape ``(n_t,)`` or ``(n_t, n_src)`` mirroring
        the input trace shape.
    """
    diff = target_pts[:, None, :] - src_pts[None, :, :]
    r = jnp.linalg.norm(diff, axis=-1)
    G = jnp.exp(1j * k * r) / (4.0 * jnp.pi * r)
    # d_{n_y} G  where  diff = x - y  =>  d/dy_i = (1/r - i k) (diff_i / r) G.
    n_dot_diff = jnp.einsum("sj,tsj->ts", src_normals, diff)
    dG_dny = (1.0 / r - 1j * k) / r * G * n_dot_diff

    w_G = G * src_weights[None, :]
    w_dG = dG_dny * src_weights[None, :]
    return w_dG @ uscat_b - w_G @ uscat_dn_b


def solve_scattering_bie_3D(
    sd: dict,
    b_radial: Callable[[np.ndarray], np.ndarray],
    source_dirs: np.ndarray,
    eta: float = None,
    p: int = None,
) -> dict:
    """Set up the interior problem and solve the coupled exterior BIE.

    Performs the full HPS+BIE coupling up to (but not including) the interior
    down-pass:

    1. Builds a ``Domain``/``PDEProblem`` matching the ``(a, q, L, kappa)``
       metadata in ``sd``.  The scattered field satisfies
       ``Lap u^s + kappa^2 (1 - b) u^s = kappa^2 b u^inc``, so the source is
       evaluated per incident direction.
    2. Permutes the (S, D) matrices to the Domain's boundary ordering and
       cross-checks the stored normals against face-identified ones.
    3. Builds the HPS solver, Cayley-transforms the top-level ItI map to DtN.
    4. Solves the exterior BIE for the scattered traces and impedance.

    Args:
        sd:           dict from :func:`load_SD_matrices_3D`.
        b_radial:     radial scattering potential; called as ``b_radial(r)``
                      on arrays of radii.
        source_dirs:  ``(n_src, 3)`` incident unit directions.
        eta:          ItI impedance parameter; defaults to ``kappa``.
        p:            interior Chebyshev order; defaults to ``q + 4``.
                      The exterior-field error is dominated by the interior
                      solve (and its Neumann trace) rather than the boundary
                      quadrature, so the default keeps the interior order
                      ahead of ``q``; ``q + 4`` puts the interior error at
                      or below the boundary-quadrature error in measured
                      sweeps over q = 4..8 and L = 1..3.

    Returns a dict with:
        ``problem``           the PDEProblem (solver built; pass ``imp`` to
                              ``jaxhps.solve`` for the interior field),
        ``boundary_points``   ``(n_bdry, 3)`` in the Domain's ordering,
        ``normals``           ``(n_bdry, 3)`` outward normals,
        ``sdp``               the permuted SD dict (for quadrature weights),
        ``imp``               ``(n_bdry, n_src)`` scattered incoming impedance,
        ``uscat_b``           ``(n_bdry, n_src)`` scattered Dirichlet trace,
        ``uscat_dn_b``        ``(n_bdry, n_src)`` scattered Neumann trace.
    """
    a, q, L, kappa = sd["a"], sd["q"], sd["L"], sd["kappa"]
    eta = float(kappa if eta is None else eta)
    p = q + 4 if p is None else p
    source_dirs = np.asarray(source_dirs, dtype=np.float64)

    root = DiscretizationNode3D(
        xmin=-a, xmax=a, ymin=-a, ymax=a, zmin=-a, zmax=a
    )
    domain = Domain(p=p, q=q, root=root, L=L)

    int_pts = np.asarray(domain.interior_points)  # (n_leaves, p^3, 3)
    b_int = b_radial(np.linalg.norm(int_pts, axis=-1))
    I_coeffs = (kappa**2 * (1.0 - b_int)).astype(np.complex128)
    phases = np.einsum("lpd,sd->lps", int_pts, source_dirs)
    uin_int = np.exp(1j * kappa * phases)  # (n_leaves, p^3, n_src)
    src = (kappa**2 * b_int[..., None] * uin_int).astype(np.complex128)

    ones = np.ones_like(I_coeffs)
    problem = PDEProblem(
        domain=domain,
        D_xx_coefficients=ones,
        D_yy_coefficients=ones,
        D_zz_coefficients=ones,
        I_coefficients=I_coeffs,
        source=src,
        use_ItI=True,
        eta=eta,
    )

    bp = np.asarray(domain.boundary_points).reshape(-1, 3)
    _, sdp = permute_to_domain(sd, bp)
    nrm = outward_normals_for_cube_boundary(bp, root)
    if not np.allclose(sdp["normals"], nrm):
        bad = float(np.linalg.norm(sdp["normals"] - nrm, axis=-1).max())
        raise RuntimeError(
            f"normals don't agree after permutation: max diff {bad:.2e}"
        )

    T_ItI = build_solver(problem, return_top_T=True)
    T_DtN = get_DtN_from_ItI_3D(jnp.asarray(T_ItI), eta)

    imp, uscat_b, uscat_dn_b = get_scattering_uscat_impedance_3D(
        S=jnp.asarray(sdp["S"]),
        D=jnp.asarray(sdp["D"]),
        T_DtN=T_DtN,
        bdry_pts=jnp.asarray(bp),
        normals=jnp.asarray(nrm),
        k=float(kappa),
        eta=eta,
        source_dirs=jnp.asarray(source_dirs),
    )
    return dict(
        problem=problem,
        boundary_points=bp,
        normals=nrm,
        sdp=sdp,
        imp=imp,
        uscat_b=np.asarray(uscat_b),
        uscat_dn_b=np.asarray(uscat_dn_b),
    )
